name: CI
on:
  push:
     branches: [ci]
  pull_request:
     branches: [ci]

env:
  RUSTFLAGS: "-Dwarnings"  # Make sure CI fails on all warnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt clippy
      - name: Code formatting check
        run: cargo fmt --verbose --check
      - name: Code check
        run: cargo clippy --all-features
      - name: Run tests
        run: cargo test --verbose --all-features
